plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

repositories {

}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()

	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

loom {
	runs {
		client {
			vmArg "-Xmx2G"
			vmArg "-Xms1G"
		}
	}
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
			pom {
				name = 'FootBox'
				description = 'Displays a wireframe hitbox in first person to show what you can stand on.'
				url = 'https://github.com/zackdcat/footbox'
				scm {
					connection = 'scm:git:git://github.com/zackdcat/footbox.git'
					developerConnection = 'scm:git:ssh://github.com/zackdcat/footbox.git'
					url = 'https://github.com/zackdcat/footbox'
				}
				issueManagement {
					system = 'GitHub'
					url = 'https://github.com/zackdcat/footbox/issues'
				}
			}
		}
	}
	repositories {

	}
}
